### ISSUE TITLE
PDFJS is not defined

### ISSUE THREAD

**Issue by chetanbuddh** [jdryg/angular-pdf-thumbnail#1]
`<pdf-thumbnail data-file="pdf.File" data-thumbnail="pdf.thumbnail_data" data-thumb-width="500"></pdf-thumbnail>`

**Comment by jdryg** [comment]
Can you be a bit more specific? Does the demo work correctly as is?

I haven't tested the directive with a newer version of pdf.js so I don't know if it works. If this is the case, I'll happily accept a PR :)
